### PR TITLE
Add composer and move HTML to Twig templates with redesigned UI

### PR DESCRIPTION
**Pull request by MusikAnimal**
This involves some refactoring of the backend code to accomodate how we
pass the data to the view. The PHP was moved to public_html to match the 
file structure on Toolforge and to keep the other files inaccessible to
the webserver.

Change the HTTP method for form submission to GET. This will allow you 
to link to results, and is more inline with the W3C specification.

Added LICENSE file, copied from atop the PHP files.

Added installation instructions to the README. Also added
credentials.php.dist to exemplify the credentials needed to run the 
application locally.

### CODE REVIEW

**Comment by MusikAnimal** [comment]
Sorry for the huge PR! The backend code is pretty much the same, just a matter of how we organized the data. Basically what was `$api` before is now `$out`, and this what gets passed to the view. I also made the keys for the array have sort of standardized values (e.g. `isp`, block`, etc.). This way, in the view, we just loop through `$out` (results from each service), and use the keys of the result set to figure out what to display.

I still need to make sure every possible value is handled in result.html.twig, hence the [WIP]. I should have all this finished up sometime tomorrow.

The code could use some comments, which I'm happy to help with in a follow-up PR.

As for the UI, here's a screenshot of the new design (adapted from the [Whois Gateway](https://tools.wmflabs.org/whois/) tool):

screenshot from 2019-01-17 01-09-53

Still some room for improvement but I think this is easier on the eyes.

Also, interesting that GitHub gave the first PR an id of #2 !

**Comment by revi** [comment]
> Also, interesting that GitHub gave the first PR an id of #2 !

[Too much information](
https://en.wikipedia.org/wiki/Information_overload) (which you might already know): issue and PR share the count. I think I once read a commentary about this as "PR is basically an issue with commits attached".

**Comment by MusikAnimal** [comment]
I think this is ready for review! There may be bugs, so please help test :)

The view code is still a bit sloppy, but I plan to make it much nicer in a subsequent PR.

> > Also, interesting that GitHub gave the first PR an id of #2 !
> issue and PR share the count. I think I once read a commentary about this as "PR is basically an issue with commits attached".

Ah! That explains it :)

**Comment by SQL-enwiki** [comment]
Works great! Merging

**Pull request merged**
